### PR TITLE
feat: Support `ESC [ @` (Insert Space)

### LINKED ISSUE #28: Editing command
Editing the line just entered has issue. inserting a character before "space" works like pressing "insert" key of the keyboard. For example enter "Hello World", place the cursor before the space, enter a character, press left arrow and again press a key. in normal mode inserting a char does not replace the character the cursor is on. but doing so, the mode suddenly changes

### PR DESCRIPTION
**Pull request by TerryGeng**
Should have fixed #28.

@mohammadkarami2023 Would you have a look?

I'm a bit worried about this commit breaking other things. I did a quick test with some common programs turned out just fine. If you can do a more thorough test, that would be the best.

### CODE REVIEW

**Comment by TerryGeng** [comment]
@mohammadkarami2023 In response to your additional report in #28, I revised the patch. Would you try again?

**Comment by mohammadkarami2023** [comment]
the problem still exists
[2024-03-03 17:11:02,807] > [terminal_buffer.py:1494] Unable to process escape sequence b'[4h'.
[2024-03-03 17:11:02,809] > [terminal_buffer.py:1494] Unable to process escape sequence b'[4l'

**Comment by TerryGeng** [comment]
I couldn't reproduce these with my bash. Would you provide more context on what command you are testing and what version of what distro you are using?

These two escape sequences `ESC [ 4 h`  and `ESC [ 4 l` are irrelevant to this PR. If there is a need, I will open new PRs.

**Comment by mohammadkarami2023** [comment]
My os is ubuntu 20.04, with Python 3.8.10, Pyqt5 5.14.1
this is the log (enter hello world, place cursor before the space, press m, press left, press j)
[2024-03-05 09:01:49,972] > [terminal_io_posix.py:113] stdin: b'h'
[2024-03-05 09:01:50,227] > [terminal_io_posix.py:113] stdin: b'e'
[2024-03-05 09:01:50,507] > [terminal_io_posix.py:113] stdin: b'l'
[2024-03-05 09:01:50,659] > [terminal_io_posix.py:113] stdin: b'l'
[2024-03-05 09:01:50,915] > [terminal_io_posix.py:113] stdin: b'o'
[2024-03-05 09:01:52,203] > [terminal_io_posix.py:113] stdin: b' '
[2024-03-05 09:01:52,603] > [terminal_io_posix.py:113] stdin: b'w'
[2024-03-05 09:01:52,859] > [terminal_io_posix.py:113] stdin: b'o'
[2024-03-05 09:01:53,075] > [terminal_io_posix.py:113] stdin: b'r'
[2024-03-05 09:01:53,819] > [terminal_io_posix.py:113] stdin: b'l'
[2024-03-05 09:01:54,323] > [terminal_io_posix.py:113] stdin: b'd'
[2024-03-05 09:01:54,819] > [terminal_io_posix.py:113] stdin: b'\x1b[D'
[2024-03-05 09:01:55,059] > [terminal_io_posix.py:113] stdin: b'\x1b[D'
[2024-03-05 09:01:55,283] > [terminal_io_posix.py:113] stdin: b'\x1b[D'
[2024-03-05 09:01:55,523] > [terminal_io_posix.py:113] stdin: b'\x1b[D'
[2024-03-05 09:01:55,715] > [terminal_io_posix.py:113] stdin: b'\x1b[D'
[2024-03-05 09:01:55,963] > [terminal_io_posix.py:113] stdin: b'\x1b[D'
[2024-03-05 09:01:58,227] > [terminal_io_posix.py:113] stdin: b'm'
[2024-03-05 09:01:59,139] > [terminal_io_posix.py:113] stdin: b'\x1b[D'
[2024-03-05 09:02:00,811] > [terminal_io_posix.py:113] stdin: b'j'
[2024-03-05 09:02:00,814] > [terminal_buffer.py:1494] Unable to process escape sequence b'[4h'.
[2024-03-05 09:02:00,816] > [terminal_buffer.py:1494] Unable to process escape sequence b'[4l'.

**Comment by mohammadkarami2023** [comment]
Could you please let me know if you could reproduce this issue?

**Comment by TerryGeng** [comment]
No, I couldn't reproduce this. I have tried my bash on both macOS and Ubuntu 22.04.

The request to implement `[4h` and `[4l` is totally valid, but I just need a suitable test case to see its behavior.

image

**Comment by mohammadkarami2023** [comment]
The problem appoears when i run the program from Spyder ide. It runs without problem when i directly use python fom terminal

**Comment by TerryGeng** [comment]
This is an interesting discovery. All I can assume is you are not using the same bash when starting inside the IDE. Spider IDE may have masked the real `/bin/bash` but replaced it with something in a sandbox. I don't really have more ideas about it since I don't use Spyder personally.

Again, the request to implement `[4h` and `[4l` is totally valid. If you can find another example of these outside Spyder, that may speed up my progress.

At this moment, I propose that I merge this PR first. You can follow up on this matter later in a new issue. What do you think?

**Comment by mohammadkarami2023** [comment]
Thanks, It is OK

**Pull request merged**
